import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Dev Overflow",
  description: "Generated by ama ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-7xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
